---
- include_tasks: Debiansetup.yml
  #when: ansible_distribution == 'Debian'
  when: ansible_os_family == 'Debian'
  
- include_tasks: RedHatsetup.yml
  when: ansible_distribution == "Amazon"

- include_tasks: RedHatsetup.yml
  when: ansible_distribution == "CentOS"
  #when: ansible_os_family == 'RedHat'

  #when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"
