- name: Check Nginx_exporter directory
  stat: path="{{nginx_exporter_execute_dir}}/nginx-prometheus-exporter"
  register: file_nginx_exporter

- name: Download and extract Nginx_exporter packages
  unarchive:
    src: "{{nginx_exporter_url}}"
    dest: "{{nginx_exporter_download_dir}}"
    owner: root
    group: root
    remote_src: yes
  when: not file_nginx_exporter.stat.exists

- name: Copy execute Nginx_exporter file
  copy:
    src: "{{nginx_exporter_download_dir}}/{{item}}"
    dest: "{{nginx_exporter_execute_dir}}"
    owner: root
    group: root
    remote_src: yes
    mode: 0755
  with_items:
    - nginx-prometheus-exporter

- name: Create Nginx_exporter service
  template:
    src: nginx-exporter.service.j2
    dest: "{{nginx_exporter_service_dir}}/nginx-exporter.service"

- name: Make sure Nginx_exporter service is running
  systemd:
    daemon_reload: yes
    state: restarted
    name: nginx-exporter
    enabled: yes
