---
# defaults file for composer
composer_path: /usr/local/bin/composer
composer_keep_updated: false
composer_version: ''
composer_home_path: '~/.composer'
composer_home_owner: root
composer_home_group: root
composer_global_packages: []
composer_add_to_path: true
