---
- hosts: dev
  become: yes
  gather_facts: true
  roles:
    #- nginx
    #- java
    - redis

# - hosts: dev
#   become: yes
#   gather_facts: true
#   roles:
    # - nginx
    # - php
    #- mysqlsv
    #- composer
    #- nodejs


# - hosts: fe
#   become: yes
#   gather_facts: true
#   roles:
#     - nginx
#     - nodejs
